name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker authentication
        run: gcloud auth configure-docker

      - name: Build and push Docker images
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/penpot-frontend ./frontend
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/penpot-frontend
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/penpot-backend ./backend
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/penpot-backend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy penpot-frontend             --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/penpot-frontend             --platform managed             --region us-central1             --allow-unauthenticated             --port 80
          gcloud run deploy penpot-backend             --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/penpot-backend             --platform managed             --region us-central1             --allow-unauthenticated             --port 8080             --set-env-vars GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }},GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }},GOOGLE_CALLBACK_URL=${{ secrets.GOOGLE_CALLBACK_URL }}
          
          # Deploy other services (database, Redis) as needed

      - name: Display service URLs
        run: |
          gcloud run services list --platform managed --region us-central1
